import { useState } from 'react';
import { CheckCircle2, MessageSquareText, Send } from 'lucide-react';
import { useListAdminSupportMessages, useUpdateSupportMessage, getListAdminSupportMessagesQueryKey, type SupportMessageStatus } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell, EmptyState, ErrorState, LoadingBlocks, StatusPill } from '@/components/portal-shell';
import { Button, PageIntro } from '@/lib/portal-ui';

export default function AdminSupportPage() {
  const query = useListAdminSupportMessages(); const [selected, setSelected] = useState<number | null>(null); const [responses, setResponses] = useState<Record<number, string>>({}); const update = useUpdateSupportMessage(); const client = useQueryClient();
  const save = (id: number, status: SupportMessageStatus) => update.mutate({ id, data: { status, adminResponse: responses[id] || undefined } }, { onSuccess: () => { client.invalidateQueries({ queryKey: getListAdminSupportMessagesQueryKey() }); setSelected(null); } });
  return <AppShell role="admin"><PageIntro eyebrow="Admin support inbox" title="Make the hard questions lighter." body="Keep company representatives moving with clear, thoughtful responses and visible status." /><div className="grid gap-6 xl:grid-cols-[.78fr_1.22fr]"><section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="border-b border-[hsl(var(--border))] p-6"><div className="flex items-center gap-3"><MessageSquareText className="size-5 text-[hsl(var(--accent-foreground))]" /><div><p className="font-mono-app text-[10px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">Messages</p><h2 className="mt-1 font-display text-2xl">Support queue</h2></div></div></div>{query.isLoading && <div className="p-5"><LoadingBlocks /></div>}{query.isError && <div className="p-5"><ErrorState onRetry={() => query.refetch()} /></div>}{!query.isLoading && !query.isError && query.data?.length === 0 && <div className="p-5"><EmptyState title="Inbox is clear." body="New company questions will appear here." /></div>}{query.data?.map((m) => <button key={m.id} onClick={() => setSelected(m.id)} className={`block w-full border-b border-[hsl(var(--border))] p-5 text-left transition-colors last:border-0 hover:bg-[hsl(var(--secondary)/.4)] ${selected === m.id ? 'bg-[hsl(var(--secondary)/.55)]' : ''}`} data-testid={`button-open-support-${m.id}`}><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-semibold">{m.subject}</p><StatusPill status={m.status} /></div><p className="mt-2 truncate text-xs text-[hsl(var(--muted-foreground))]">{m.name} · {m.email}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{m.message}</p></button>)}</section><section>{selected == null ? <div className="grid min-h-[420px] place-items-center rounded-[24px] border border-dashed border-[hsl(var(--border))] bg-[hsl(var(--card)/.45)] p-8 text-center"><div><MessageSquareText className="mx-auto size-8 text-[hsl(var(--muted-foreground))]" /><p className="mt-4 font-display text-2xl">Select a message.</p><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Read the full context and respond from here.</p></div></div> : <SupportPanel message={query.data?.find((m) => m.id === selected)} response={responses[selected] || ''} setResponse={(v) => setResponses((r) => ({ ...r, [selected]: v }))} onSave={save} isPending={update.isPending} />}</section></div></AppShell>;
}
function SupportPanel({ message, response, setResponse, onSave, isPending }: { message: { id: number; name: string; email: string; subject: string; message: string; status: string; adminResponse: string | null } | undefined; response: string; setResponse: (v: string) => void; onSave: (id: number, status: SupportMessageStatus) => void; isPending: boolean }) {
  if (!message) return null;
  return <div className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 sm:p-8"><div className="flex items-start justify-between gap-4 border-b border-[hsl(var(--border))] pb-6"><div><p className="font-mono-app text-[10px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">From {message.name}</p><h2 className="mt-2 font-display text-3xl">{message.subject}</h2><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{message.email}</p></div><StatusPill status={message.status} /></div><p className="py-7 text-sm leading-7">{message.message}</p>{message.adminResponse && <div className="mb-6 rounded-xl bg-[hsl(var(--secondary))] p-4 text-sm leading-6"><p className="font-mono-app text-[10px] uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">Previous response</p><p className="mt-2">{message.adminResponse}</p></div>}<label className="grid gap-2"><span className="text-xs font-semibold">Response</span><textarea className="form-input min-h-[150px] resize-y" value={response} onChange={(e) => setResponse(e.target.value)} placeholder="Write a clear response for the company representative..." data-testid="textarea-support-response" /></label><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => onSave(message.id, 'in_progress')} disabled={isPending} secondary testId="button-support-progress">Mark in progress</Button><Button onClick={() => onSave(message.id, 'resolved')} disabled={isPending} testId="button-support-resolve">{isPending ? 'Saving…' : 'Respond & resolve'} <CheckCircle2 className="size-4" /></Button><Button onClick={() => onSave(message.id, 'open')} disabled={isPending} secondary testId="button-support-reopen">Keep open <Send className="size-4" /></Button></div></div>;
}