import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CircleHelp, ShieldCheck } from 'lucide-react';
import { useCreateAssessment, type AssessmentInput } from '@workspace/api-client-react';
import { useLocation } from 'wouter';
import { AppShell } from '@/components/portal-shell';
import { Button, Field, InfoBox, PageIntro, SelectField } from '@/lib/portal-ui';

type FormState = { companyName: string; cin: string; companyType: string; financialYear: string; registeredState: string; industry: string; netWorth: string; turnover: string; netProfit: string; profitYear1: string; profitYear2: string; profitYear3: string; csrPolicyStatus: string; governanceStatus: string; annualActionPlanStatus: string; implementingAgencyStatus: string; csrFocusAreas: string; additionalNotes: string };
const blank: FormState = { companyName: '', cin: '', companyType: '', financialYear: '2024-25', registeredState: '', industry: '', netWorth: '', turnover: '', netProfit: '', profitYear1: '', profitYear2: '', profitYear3: '', csrPolicyStatus: '', governanceStatus: '', annualActionPlanStatus: '', implementingAgencyStatus: '', csrFocusAreas: '', additionalNotes: '' };
const steps = ['Company information', 'Financial eligibility', 'Indicative obligation', 'CSR readiness', 'Review & submit'];
const companyTypes: Array<[string, string]> = [['private_limited', 'Private limited'], ['public_limited', 'Public limited'], ['llp', 'LLP'], ['section_8', 'Section 8 company'], ['other', 'Other']];
const readiness: Array<[string, string]> = [['in_place', 'In place'], ['in_progress', 'In progress'], ['not_started', 'Not started'], ['not_applicable', 'Not applicable']];
const states = ['Andhra Pradesh','Delhi','Gujarat','Karnataka','Kerala','Maharashtra','Tamil Nadu','Telangana','Uttar Pradesh','West Bengal','Other'].map((s) => [s, s] as [string,string]);
const numberValue = (v: string) => v.trim() === '' ? undefined : Number(v);

export default function ApplyPage() {
  const [step, setStep] = useState(0); const [form, setForm] = useState<FormState>(blank); const [error, setError] = useState(''); const [, setLocation] = useLocation(); const create = useCreateAssessment();
  const update = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const obligation = useMemo(() => { const values = [form.profitYear1, form.profitYear2, form.profitYear3].map(Number); return values.every((v, i) => form[['profitYear1','profitYear2','profitYear3'][i] as keyof FormState] !== '' && Number.isFinite(v)) ? (values.reduce((a,b) => a + b, 0) / 3) * .02 : null; }, [form]);
  const next = () => { setError(''); if (step === 0 && (!form.companyName || !form.cin || !form.companyType || !form.financialYear)) return setError('Complete the required company fields before continuing.'); if (step === 1 && [form.netWorth, form.turnover, form.netProfit].some((v) => v === '' || Number(v) < 0)) return setError('Enter all three financial values as zero or more crore rupees.'); setStep((v) => Math.min(4, v + 1)); };
  const submit = () => { setError(''); const data: AssessmentInput = { companyName: form.companyName.trim(), cin: form.cin.trim(), companyType: form.companyType as AssessmentInput['companyType'], financialYear: form.financialYear, netWorth: Number(form.netWorth), turnover: Number(form.turnover), netProfit: Number(form.netProfit), ...(form.registeredState ? { registeredState: form.registeredState } : {}), ...(form.industry ? { industry: form.industry } : {}), ...(numberValue(form.profitYear1) !== undefined ? { profitYear1: numberValue(form.profitYear1) } : {}), ...(numberValue(form.profitYear2) !== undefined ? { profitYear2: numberValue(form.profitYear2) } : {}), ...(numberValue(form.profitYear3) !== undefined ? { profitYear3: numberValue(form.profitYear3) } : {}), ...(form.csrPolicyStatus ? { csrPolicyStatus: form.csrPolicyStatus } : {}), ...(form.governanceStatus ? { governanceStatus: form.governanceStatus } : {}), ...(form.annualActionPlanStatus ? { annualActionPlanStatus: form.annualActionPlanStatus } : {}), ...(form.implementingAgencyStatus ? { implementingAgencyStatus: form.implementingAgencyStatus } : {}), ...(form.csrFocusAreas ? { csrFocusAreas: form.csrFocusAreas.split(',').map((s) => s.trim()).filter(Boolean) } : {}), ...(form.additionalNotes ? { additionalNotes: form.additionalNotes } : {}) }; create.mutate({ data }, { onSuccess: (assessment) => setLocation(`/user/assessment/${assessment.id}`), onError: () => setError('We could not submit this assessment. Check the details and try again.') }); };
  return <AppShell role="user"><PageIntro eyebrow="New assessment" title="Build your CSR picture." body="Five short steps. Financial values are in crore rupees. Optional sections help make the result more useful." back="/user/dashboard" /><div className="mx-auto max-w-5xl"><div className="mb-8 grid grid-cols-5 gap-1 sm:gap-3">{steps.map((label, i) => <div key={label} className="relative"><div className={`h-1.5 rounded-full ${i <= step ? 'bg-[hsl(var(--accent))]' : 'bg-[hsl(var(--muted))]'}`} /><p className={`mt-2 hidden text-[10px] leading-4 sm:block ${i === step ? 'font-semibold text-[hsl(var(--primary))]' : 'text-[hsl(var(--muted-foreground))]'}`}>{label}</p><span className="mt-2 block text-center font-mono-app text-[9px] text-[hsl(var(--muted-foreground))] sm:hidden">0{i + 1}</span></div>)}</div><section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] shadow-[0_10px_28px_hsl(var(--primary)/.05)]"><div className="border-b border-[hsl(var(--border))] px-6 py-5 sm:px-8"><p className="font-mono-app text-[10px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">Step 0{step + 1}</p><h2 className="mt-2 font-display text-3xl tracking-[-.04em]">{steps[step]}</h2></div><div className="p-6 sm:p-8">
    {step === 0 && <div className="grid gap-5 sm:grid-cols-2"><Field label="Company name *"><input className="form-input" value={form.companyName} onChange={(e) => update('companyName', e.target.value)} placeholder="e.g. Meridian Textiles Private Limited" data-testid="input-company-name" /></Field><Field label="Corporate Identification Number (CIN) *"><input className="form-input" value={form.cin} onChange={(e) => update('cin', e.target.value.toUpperCase())} placeholder="e.g. U17100MH2012PTC000000" data-testid="input-cin" /></Field><SelectField label="Company type *" value={form.companyType} onChange={(v) => update('companyType', v)} options={companyTypes} testId="select-company-type" /><Field label="Financial year *" hint="Use the format YYYY-YY."><input className="form-input" value={form.financialYear} onChange={(e) => update('financialYear', e.target.value)} placeholder="2024-25" data-testid="input-financial-year" /></Field><SelectField label="Registered state" value={form.registeredState} onChange={(v) => update('registeredState', v)} options={states} testId="select-registered-state" /><Field label="Industry"><input className="form-input" value={form.industry} onChange={(e) => update('industry', e.target.value)} placeholder="e.g. manufacturing, technology" data-testid="input-industry" /></Field></div>}
    {step === 1 && <div><InfoBox>Enter the latest financial values in <strong>crore rupees</strong>. CivicPath checks each value against the statutory thresholds: net worth ₹500 crore, turnover ₹1,000 crore, or net profit ₹5 crore.</InfoBox><div className="mt-6 grid gap-5 sm:grid-cols-3"><Field label="Net worth (₹ crore) *"><input type="number" min="0" className="form-input" value={form.netWorth} onChange={(e) => update('netWorth', e.target.value)} placeholder="0.00" data-testid="input-net-worth" /></Field><Field label="Turnover (₹ crore) *"><input type="number" min="0" className="form-input" value={form.turnover} onChange={(e) => update('turnover', e.target.value)} placeholder="0.00" data-testid="input-turnover" /></Field><Field label="Net profit (₹ crore) *"><input type="number" min="0" className="form-input" value={form.netProfit} onChange={(e) => update('netProfit', e.target.value)} placeholder="0.00" data-testid="input-net-profit" /></Field></div><div className="mt-8 border-t border-[hsl(var(--border))] pt-6"><p className="text-sm font-semibold">Optional profit history</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Add all three years in the next step to calculate an indicative 2% obligation.</p></div></div>}
    {step === 2 && <div><InfoBox>When all three profit years are entered, the indicative obligation is calculated as their average multiplied by 2%. This is a guide only, not a final legal or financial determination.</InfoBox><div className="mt-6 grid gap-5 sm:grid-cols-3"><Field label="Profit year 1 (₹ crore)"><input type="number" min="0" className="form-input" value={form.profitYear1} onChange={(e) => update('profitYear1', e.target.value)} placeholder="Optional" data-testid="input-profit-year-1" /></Field><Field label="Profit year 2 (₹ crore)"><input type="number" min="0" className="form-input" value={form.profitYear2} onChange={(e) => update('profitYear2', e.target.value)} placeholder="Optional" data-testid="input-profit-year-2" /></Field><Field label="Profit year 3 (₹ crore)"><input type="number" min="0" className="form-input" value={form.profitYear3} onChange={(e) => update('profitYear3', e.target.value)} placeholder="Optional" data-testid="input-profit-year-3" /></Field></div>{obligation != null && <div className="mt-8 rounded-2xl bg-[hsl(var(--secondary))] p-5"><p className="font-mono-app text-[10px] uppercase tracking-[.13em] text-[hsl(var(--muted-foreground))]">Indicative obligation</p><p className="mt-2 font-display text-4xl text-[hsl(var(--primary))]">₹{obligation.toFixed(2)} crore</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Average of the three entered profit years × 2%</p></div>}</div>}
    {step === 3 && <div><div className="grid gap-5 sm:grid-cols-2"><SelectField label="CSR policy status" value={form.csrPolicyStatus} onChange={(v) => update('csrPolicyStatus', v)} options={readiness} testId="select-csr-policy-status" /><SelectField label="Governance status" value={form.governanceStatus} onChange={(v) => update('governanceStatus', v)} options={readiness} testId="select-governance-status" /><SelectField label="Annual action plan status" value={form.annualActionPlanStatus} onChange={(v) => update('annualActionPlanStatus', v)} options={readiness} testId="select-annual-action-plan-status" /><SelectField label="Implementing agency status" value={form.implementingAgencyStatus} onChange={(v) => update('implementingAgencyStatus', v)} options={readiness} testId="select-implementing-agency-status" /><Field label="CSR focus areas" hint="Separate focus areas with commas."><input className="form-input" value={form.csrFocusAreas} onChange={(e) => update('csrFocusAreas', e.target.value)} placeholder="Education, healthcare, environment" data-testid="input-csr-focus-areas" /></Field><Field label="Additional notes"><textarea className="form-input min-h-[110px] resize-y" value={form.additionalNotes} onChange={(e) => update('additionalNotes', e.target.value)} placeholder="Anything the reviewer should know..." data-testid="textarea-additional-notes" /></Field></div></div>}
    {step === 4 && <div className="space-y-6"><InfoBox><span>Review your entries before submitting. The server will decide CSR applicability and save a timestamped assessment record for independent review.</span></InfoBox><div className="grid gap-3 sm:grid-cols-2">{[['Company', form.companyName],['CIN', form.cin],['Type', companyTypes.find(([v]) => v === form.companyType)?.[1] ?? '—'],['Financial year', form.financialYear],['Net worth', `₹${form.netWorth || '—'} crore`],['Turnover', `₹${form.turnover || '—'} crore`],['Net profit', `₹${form.netProfit || '—'} crore`],['Indicative obligation', obligation != null ? `₹${obligation.toFixed(2)} crore` : 'Not calculated']].map(([label,value]) => <div key={label} className="rounded-xl bg-[hsl(var(--secondary)/.55)] p-4"><p className="font-mono-app text-[9px] uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="flex items-start gap-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[hsl(155_42%_43%)]" /> Your information is only used to assess CSR applicability and coordinate review.</div></div>}
    {error && <p className="mt-6 rounded-xl bg-[hsl(var(--destructive)/.08)] px-4 py-3 text-sm text-[hsl(var(--destructive))]" data-testid="text-assessment-error">{error}</p>}</div><div className="flex flex-col-reverse justify-between gap-3 border-t border-[hsl(var(--border))] px-6 py-5 sm:flex-row sm:px-8">{step > 0 ? <Button secondary onClick={() => setStep((v) => v - 1)} testId="button-previous-step"><ArrowLeft className="size-4" /> Previous</Button> : <span />}{step < 4 ? <Button onClick={next} testId="button-next-step">Continue <ArrowRight className="size-4" /></Button> : <Button onClick={submit} disabled={create.isPending} testId="button-submit-assessment">{create.isPending ? 'Submitting…' : 'Submit assessment'} {!create.isPending && <Check className="size-4" />}</Button>}</div></section><p className="mt-5 flex items-center gap-2 text-xs text-[hsl(var(--muted-foreground))]"><CircleHelp className="size-4" /> Unsure about a field? You can contact support after submitting.</p></div></AppShell>;
}