import { ArrowLeft, ArrowRight, ShieldCheck } from 'lucide-react';
import * as React from 'react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useLocation } from 'wouter';
import { useUser } from '@clerk/react';
import { useCreateApplication, type ApplicationInput } from '@workspace/api-client-react';
import { AppShell } from '@/components/portal-shell';

const regions = ['North district', 'East district', 'Central district', 'South district', 'West district'];
const programs = ['Household essentials', 'Work & training support', 'Health access', 'Housing stability'];

export default function ApplyPage() {
  const [, setLocation] = useLocation();
  const [submitError, setSubmitError] = useState('');
  const { user } = useUser();
  const createApplication = useCreateApplication();
  const email = user?.primaryEmailAddress?.emailAddress ?? '';
  const form = useForm<ApplicationInput>({ defaultValues: { applicantName: '', email, phone: '', program: '', region: '', annualIncome: 0, householdSize: 1, employmentStatus: 'employed', hasDisability: false, requestedSupport: '', notes: '' } });
  React.useEffect(() => {
    if (email && !form.getValues('email')) form.setValue('email', email);
  }, [email, form]);
  const onSubmit = (data: ApplicationInput) => {
    setSubmitError('');
    createApplication.mutate({ data }, { onSuccess: (application) => setLocation(`/user/result/${application.id}`), onError: () => setSubmitError('We couldn’t submit this yet. Please check your details and try again.') });
  };
  return <AppShell role="user"><div className="mx-auto max-w-4xl animate-rise-in"><Link href="/user/dashboard" className="mb-7 inline-flex items-center gap-2 text-sm font-medium text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]" data-testid="link-back-dashboard"><ArrowLeft className="size-4" /> Back to overview</Link><div className="mb-9"><p className="font-mono-app text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent-foreground)/.68)]">Step 1 of 1 · About you</p><h1 className="mt-3 font-display text-5xl leading-none tracking-[-.055em] text-[hsl(var(--primary))]">Tell us what you need.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[hsl(var(--muted-foreground))]">This takes about five minutes. Your answers help us understand what support may fit — there are no wrong answers.</p></div>
    <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
      <section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-[0_8px_24px_hsl(var(--primary)/.04)] sm:p-8"><SectionTitle number="01" title="Your details" body="How can we reach you if we need to follow up?" /><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Full name" error={form.formState.errors.applicantName?.message}><input {...form.register('applicantName', { required: 'Please add your name.', minLength: { value: 2, message: 'Please add your full name.' } })} placeholder="Your name" className="form-input" data-testid="input-applicant-name" /></Field><Field label="Email address"><input type="email" readOnly {...form.register('email', { required: 'Please add your email.' })} className="form-input opacity-75" data-testid="input-applicant-email" /></Field><Field label="Phone number" error={form.formState.errors.phone?.message}><input {...form.register('phone', { required: 'Please add a phone number.', minLength: { value: 7, message: 'Please enter a valid phone number.' } })} placeholder="(555) 123-4567" className="form-input" data-testid="input-applicant-phone" /></Field><Field label="Region"><select {...form.register('region', { required: 'Choose your region.' })} className="form-input" data-testid="select-applicant-region"><option value="">Choose a region</option>{regions.map((region) => <option key={region} value={region}>{region}</option>)}</select></Field></div></section>
      <section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-[0_8px_24px_hsl(var(--primary)/.04)] sm:p-8"><SectionTitle number="02" title="Your situation" body="A little context helps us point you in the right direction." /><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Program you’re interested in"><select {...form.register('program', { required: 'Choose a program.' })} className="form-input" data-testid="select-applicant-program"><option value="">Choose a program</option>{programs.map((program) => <option key={program} value={program}>{program}</option>)}</select></Field><Field label="Household size"><input type="number" min="1" {...form.register('householdSize', { required: true, valueAsNumber: true, min: 1 })} className="form-input" data-testid="input-household-size" /></Field><Field label="Annual household income"><div className="relative"><span className="pointer-events-none absolute left-4 top-3.5 text-[hsl(var(--muted-foreground))]">$</span><input type="number" min="0" {...form.register('annualIncome', { required: true, valueAsNumber: true, min: 0 })} className="form-input pl-8" placeholder="0" data-testid="input-annual-income" /></div><span className="mt-1 block text-xs text-[hsl(var(--muted-foreground))]">Before taxes, for the last 12 months</span></Field><Field label="Employment status"><select {...form.register('employmentStatus')} className="form-input" data-testid="select-employment-status"><option value="employed">Employed</option><option value="self_employed">Self-employed</option><option value="unemployed">Not currently employed</option><option value="student">Student</option><option value="retired">Retired</option></select></Field></div><label className="mt-6 flex cursor-pointer items-start gap-3 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--background)/.55)] p-4"><input type="checkbox" {...form.register('hasDisability')} className="mt-1 size-4 accent-[hsl(var(--accent))]" data-testid="checkbox-disability" /><span><span className="block text-sm font-semibold">Someone in my household has a disability</span><span className="mt-1 block text-xs leading-5 text-[hsl(var(--muted-foreground))]">This can help us identify additional support pathways. You do not need to share any details.</span></span></label></section>
      <section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 shadow-[0_8px_24px_hsl(var(--primary)/.04)] sm:p-8"><SectionTitle number="03" title="What would help?" body="Use your own words. We’ll read this with care." /><div className="mt-7 space-y-5"><Field label="Support you’re requesting"><textarea {...form.register('requestedSupport', { required: 'Tell us what support you are looking for.', minLength: { value: 2, message: 'Please add a little more detail.' } })} placeholder="For example: help with monthly household costs…" className="form-input min-h-[104px] resize-y py-3" data-testid="textarea-requested-support" /></Field><Field label="Anything else you’d like us to know?"><textarea {...form.register('notes')} placeholder="Optional" className="form-input min-h-[88px] resize-y py-3" data-testid="textarea-application-notes" /></Field></div></section>
      <div className="flex flex-col-reverse items-start justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[hsl(var(--chart-3))]" /><span>Your information is private and only used for this application.</span></div><button type="submit" disabled={createApplication.isPending} className="group flex w-full items-center justify-center gap-3 rounded-xl bg-[hsl(var(--primary))] px-6 py-3.5 text-sm font-semibold text-[hsl(var(--primary-foreground))] transition-all hover:-translate-y-0.5 disabled:opacity-65 sm:w-auto" data-testid="button-submit-application">{createApplication.isPending ? 'Submitting…' : 'Submit application'} {!createApplication.isPending && <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" />}</button></div>{submitError && <p className="rounded-xl bg-[hsl(var(--destructive)/.08)] px-4 py-3 text-sm text-[hsl(var(--destructive))]" data-testid="text-submit-error">{submitError}</p>}</form>
  </div></AppShell>;
}

function SectionTitle({ number, title, body }: { number: string; title: string; body: string }) { return <div className="flex gap-4"><span className="font-mono-app text-xs text-[hsl(var(--accent-foreground)/.65)]">{number}</span><div><h2 className="font-display text-3xl tracking-[-.04em] text-[hsl(var(--primary))]">{title}</h2><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{body}</p></div></div>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.08em] text-[hsl(var(--muted-foreground))]">{label}</span>{children}{error && <span className="mt-1 block text-xs text-[hsl(var(--destructive))]" data-testid="text-field-error">{error}</span>}</label>; }