import { LockKeyhole, ShieldCheck, UserRound } from 'lucide-react';
import { useUser } from '@clerk/react';
import { AppShell } from '@/components/portal-shell';
import { PageIntro } from '@/lib/portal-ui';

export default function ProfilePage() {
  const { user } = useUser(); const email = user?.primaryEmailAddress?.emailAddress ?? 'Your verified email';
  return <AppShell role="user"><PageIntro eyebrow="Profile & privacy" title="Your account context." body="Clerk securely manages your identity. CivicPath stores only the company assessment and support information needed for this portal." /><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 sm:p-8"><div className="flex items-center gap-4 border-b border-[hsl(var(--border))] pb-6"><div className="grid size-14 place-items-center rounded-2xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><UserRound className="size-6" /></div><div><h2 className="font-display text-2xl">{user?.fullName || 'Company representative'}</h2><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{email}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Detail label="Account status" value="Verified with Clerk" /><Detail label="Sign-in email" value={email} /></div><p className="mt-7 text-xs leading-6 text-[hsl(var(--muted-foreground))]">To change your password, email, or verification settings, use your Clerk account controls.</p></section><aside className="space-y-5"><div className="rounded-[24px] bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))]"><ShieldCheck className="size-6 text-[hsl(var(--accent))]" /><h2 className="mt-5 font-display text-3xl">A narrow data footprint.</h2><p className="mt-3 text-sm leading-6 text-[hsl(var(--primary-foreground)/.62)]">We use your data to assess CSR applicability, show your record, and answer support messages. Admin-only notes remain private.</p></div><div className="flex items-start gap-3 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 text-xs leading-6 text-[hsl(var(--muted-foreground))]"><LockKeyhole className="mt-1 size-4 shrink-0 text-[hsl(155_42%_43%)]" /> Secure sessions and account verification are handled by CivicPath Auth.</div></aside></div></AppShell>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[hsl(var(--secondary)/.55)] p-4"><p className="font-mono-app text-[9px] uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-2 truncate text-sm font-semibold">{value}</p></div>; }