import { ArrowRight, CheckCircle2, Circle, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import { useListAssessments } from '@workspace/api-client-react';
import { AppShell, EmptyState, LoadingBlocks, StatusPill } from '@/components/portal-shell';
import { InfoBox, PageIntro } from '@/lib/portal-ui';

export default function RoadmapPage() {
  const query = useListAssessments(); const a = query.data?.[0];
  return <AppShell role="user"><PageIntro eyebrow="Compliance roadmap" title="A practical path from result to readiness." body="Use this as a working checklist. It adapts to the latest assessment in your company workspace." />{query.isLoading && <LoadingBlocks />}{!query.isLoading && !a && <EmptyState title="Your roadmap begins with an assessment." body="Submit a company assessment first. Once the server records your result, your roadmap will appear here." />}{a && <div className="grid gap-6 xl:grid-cols-[1fr_.72fr]"><section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-[hsl(var(--border))] pb-6"><div><p className="font-mono-app text-[10px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">Latest assessment</p><h2 className="mt-2 font-display text-3xl">{a.companyName}</h2></div><StatusPill status={a.csrApplicable ? 'applicable' : 'not_applicable'} label={a.csrApplicable ? 'Applicable' : 'Not applicable'} /></div><div className="mt-8 space-y-8"><RoadmapItem done title="Record the financial assessment" body="Your net worth, turnover, and net profit have been assessed against the three statutory thresholds." /><RoadmapItem done={a.reviewStatus !== 'pending'} title="Complete independent review" body={a.reviewStatus === 'pending' ? 'A CivicPath reviewer will check the assessment and add a review status here.' : 'The reviewer has recorded a decision. Any public note appears on your assessment detail.'} /><RoadmapItem done={Boolean(a.csrPolicyStatus && a.governanceStatus)} title="Confirm CSR governance foundations" body="Keep your CSR policy, governance ownership, and annual action plan aligned with the applicability result." /><RoadmapItem done={Boolean(a.implementingAgencyStatus)} title="Prepare implementation details" body="If applicable, document your implementing agency and the focus areas your company intends to support." /></div></section><aside className="space-y-6"><div className="rounded-[24px] bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))] sm:p-7"><ShieldCheck className="size-6 text-[hsl(var(--accent))]" /><h2 className="mt-5 font-display text-3xl">Keep the record useful.</h2><p className="mt-3 text-sm leading-6 text-[hsl(var(--primary-foreground)/.63)]">The roadmap is a conversation starter, not a substitute for professional advice. Keep your source figures and governance records close.</p><Link href={`/user/assessment/${a.id}`} className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[hsl(var(--accent))]" data-testid="link-roadmap-assessment">Review assessment <ArrowRight className="size-4" /></Link></div><InfoBox><span>Need help interpreting a field or review note? <Link href="/user/support" className="font-semibold underline" data-testid="link-roadmap-support">Contact support</Link>.</span></InfoBox></aside></div>}</AppShell>;
}
function RoadmapItem({ done, title, body }: { done: boolean; title: string; body: string }) { return <div className="flex gap-4"><div className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-full ${done ? 'bg-[hsl(155_38%_89%)] text-[hsl(155_40%_29%)]' : 'bg-[hsl(var(--secondary))] text-[hsl(var(--muted-foreground))]'}`}>{done ? <CheckCircle2 className="size-4" /> : <Circle className="size-4" />}</div><div><p className="text-sm font-semibold">{title}</p><p className="mt-2 max-w-xl text-sm leading-6 text-[hsl(var(--muted-foreground))]">{body}</p></div></div>; }