import { ArrowRight, CalendarDays, CheckCircle2, Clock3, FileText, HelpCircle, MapPin, Plus } from 'lucide-react';
import * as React from 'react';
import { Link } from 'wouter';
import { useListApplications } from '@workspace/api-client-react';
import { AppShell, EmptyState, ErrorState, LoadingBlocks, StatusPill } from '@/components/portal-shell';

export default function UserDashboard() {
  const [email] = React.useState(
    () => window.sessionStorage.getItem('civicpath-user-email') ?? 'maya.patel@example.com',
  );
  const applicationsQuery = useListApplications({ email });
  const applications = applicationsQuery.data ?? [];
  const current = applications[0];
  return <AppShell role="user">
    <div className="animate-rise-in">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono-app text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent-foreground)/.68)]">Tuesday, 14 October 2025</p><h1 className="mt-3 font-display text-5xl leading-none tracking-[-.055em] text-[hsl(var(--primary))]">Good morning.</h1><p className="mt-4 text-sm text-[hsl(var(--muted-foreground))]">Here’s the latest on your support journey.</p></div><Link href="/user/apply" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-3 text-sm font-semibold text-[hsl(var(--primary-foreground))] transition-all hover:-translate-y-0.5" data-testid="link-new-application"><Plus className="size-4" /> New application</Link></div>
      {applicationsQuery.isLoading && <div className="mt-10"><LoadingBlocks /></div>}
      {applicationsQuery.isError && <div className="mt-10"><ErrorState onRetry={() => applicationsQuery.refetch()} /></div>}
      {!applicationsQuery.isLoading && !applicationsQuery.isError && !current && <div className="mt-10"><EmptyState title="Your space is ready." body="When you start an application, it will show up here with every update and next step." /><div className="mt-5 text-center"><Link href="/user/apply" className="inline-flex items-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-5 py-3 text-sm font-semibold text-[hsl(var(--primary-foreground))]" data-testid="link-empty-start">Start your application <ArrowRight className="size-4" /></Link></div></div>}
      {current && <div className="mt-10 grid gap-6 xl:grid-cols-[1.4fr_.6fr]">
        <div className="space-y-6">
          <section className="overflow-hidden rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] shadow-[0_10px_28px_hsl(var(--primary)/.05)]">
            <div className="border-b border-[hsl(var(--border))] px-6 py-5 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono-app text-[10px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">Application #{String(current.id).padStart(5, '0')}</p><h2 className="mt-2 font-display text-3xl tracking-[-.04em]">{current.program}</h2></div><StatusPill status={current.status} /></div></div>
            <div className="px-6 py-7 sm:px-8"><div className="relative flex justify-between"><div className="absolute left-4 right-4 top-4 h-px bg-[hsl(var(--border))]" /><div className="absolute left-4 top-4 h-px w-[50%] bg-[hsl(var(--accent))]" /><ProgressStep icon={<CheckCircle2 />} label="Submitted" done /><ProgressStep icon={<Clock3 />} label="In review" done={current.status !== 'pending'} active={current.status === 'pending'} /><ProgressStep icon={<FileText />} label="Decision" done={current.status !== 'pending'} /></div><div className="mt-8 rounded-2xl bg-[hsl(var(--secondary)/.65)] p-4 text-sm leading-6 text-[hsl(var(--muted-foreground))]"><span className="font-semibold text-[hsl(var(--foreground))]">{current.status === 'pending' ? 'Your application is with the team.' : 'Your application has been reviewed.'}</span> We’ll keep this page updated as things move forward.</div></div>
            <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[hsl(var(--border))] px-6 py-4 sm:px-8"><span className="flex items-center gap-2 text-xs text-[hsl(var(--muted-foreground))]"><CalendarDays className="size-4" /> Submitted {new Date(current.submittedAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span><Link href={`/user/result/${current.id}`} className="flex items-center gap-2 text-sm font-semibold text-[hsl(var(--primary))]" data-testid={`link-view-result-${current.id}`}>View details <ArrowRight className="size-4" /></Link></div>
          </section>
          <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5"><div className="flex items-center gap-2 text-[hsl(var(--muted-foreground))]"><MapPin className="size-4" /><span className="font-mono-app text-[10px] uppercase tracking-[.13em]">Region</span></div><p className="mt-5 font-display text-2xl">{current.region}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">From your application</p></div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5"><div className="flex items-center gap-2 text-[hsl(var(--muted-foreground))]"><HelpCircle className="size-4" /><span className="font-mono-app text-[10px] uppercase tracking-[.13em]">Need a hand?</span></div><p className="mt-5 font-display text-2xl">We’re here.</p><button className="mt-1 text-left text-xs font-semibold text-[hsl(var(--primary))]" onClick={() => window.alert('For the demo, please contact your local CivicPath support desk.')} data-testid="button-contact-support">Contact support <ArrowRight className="ml-1 inline size-3" /></button></div></section>
        </div>
        <aside className="rounded-[24px] bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))] sm:p-7"><div className="flex items-center justify-between"><span className="font-mono-app text-[10px] uppercase tracking-[.14em] text-[hsl(var(--primary-foreground)/.56)]">Your current read</span><span className="size-2 rounded-full bg-[hsl(var(--accent))]" /></div><p className="mt-12 font-display text-4xl leading-none">{current.eligibilityStatus === 'eligible' ? 'Likely eligible' : current.eligibilityStatus === 'review' ? 'Needs a closer look' : 'Not eligible right now'}</p><p className="mt-5 text-sm leading-6 text-[hsl(var(--primary-foreground)/.65)]">{current.eligibilityStatus === 'eligible' ? 'Your answers line up with the initial criteria for this program.' : 'A reviewer will help make sense of what comes next.'}</p><div className="mt-12 border-t border-[hsl(var(--primary-foreground)/.15)] pt-5"><div className="flex items-end justify-between"><span className="text-xs text-[hsl(var(--primary-foreground)/.58)]">Eligibility score</span><span className="font-mono-app text-2xl text-[hsl(var(--accent))]">{current.eligibilityScore}<small className="text-xs text-[hsl(var(--primary-foreground)/.5)]"> / 100</small></span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[hsl(var(--primary-foreground)/.14)]"><div className="h-full rounded-full bg-[hsl(var(--accent))] transition-all duration-700" style={{ width: `${Math.min(current.eligibilityScore, 100)}%` }} /></div></div><Link href={`/user/result/${current.id}`} className="mt-7 flex items-center justify-between rounded-xl bg-[hsl(var(--primary-foreground)/.1)] px-4 py-3 text-sm font-semibold transition-colors hover:bg-[hsl(var(--primary-foreground)/.16)]" data-testid={`link-result-card-${current.id}`}>Read your result <ArrowRight className="size-4" /></Link></aside>
      </div>}
    </div>
  </AppShell>;
}

function ProgressStep({ icon, label, done, active }: { icon: React.ReactNode; label: string; done?: boolean; active?: boolean }) {
  return <div className="relative z-10 flex w-1/3 flex-col items-center gap-2 text-center"><div className={`grid size-8 place-items-center rounded-full border-4 border-[hsl(var(--card))] ${done ? 'bg-[hsl(var(--chart-3))] text-[hsl(var(--card))]' : active ? 'bg-[hsl(var(--accent))] text-[hsl(var(--accent-foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]'}`}>{icon}</div><span className={`text-[10px] font-semibold ${active ? 'text-[hsl(var(--foreground))]' : 'text-[hsl(var(--muted-foreground))]'}`}>{label}</span></div>;
}