import { type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, Check, Info } from 'lucide-react';
import { Link } from 'wouter';
import { StatusPill } from '@/components/portal-shell';

export function PageIntro({ eyebrow, title, body, back }: { eyebrow: string; title: string; body?: string; back?: string }) {
  return <div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end animate-rise-in">{<div>{back && <Link href={back} className="mb-5 inline-flex items-center gap-2 text-xs font-medium text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]" data-testid="link-page-back"><ArrowLeft className="size-4" /> Back</Link>}<p className="font-mono-app text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent-foreground)/.7)]">{eyebrow}</p><h1 className="mt-3 max-w-3xl font-display text-5xl leading-[.96] tracking-[-.055em] text-[hsl(var(--primary))]">{title}</h1>{body && <p className="mt-4 max-w-2xl text-sm leading-7 text-[hsl(var(--muted-foreground))]">{body}</p>}</div>}</div>;
}
export function Field({ label, hint, children, testId }: { label: string; hint?: string; children: ReactNode; testId?: string }) {
  return <label className="grid gap-2" data-testid={testId}><span className="text-xs font-semibold text-[hsl(var(--foreground))]">{label}</span>{children}{hint && <span className="text-[11px] leading-5 text-[hsl(var(--muted-foreground))]">{hint}</span>}</label>;
}
export function SelectField({ label, value, onChange, options, testId }: { label: string; value: string; onChange: (v: string) => void; options: Array<[string, string]>; testId: string }) {
  return <Field label={label} testId={`field-${testId}`}><select value={value} onChange={(e) => onChange(e.target.value)} className="form-input" data-testid={testId}><option value="">Select one</option>{options.map(([v, t]) => <option key={v} value={v}>{t}</option>)}</select></Field>;
}
export function Button({ children, secondary = false, onClick, disabled, testId, type = 'button' }: { children: ReactNode; secondary?: boolean; onClick?: () => void; disabled?: boolean; testId: string; type?: 'button' | 'submit' }) {
  return <button type={type} onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold transition-all hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-55 ${secondary ? 'border border-[hsl(var(--border))] bg-[hsl(var(--card))] text-[hsl(var(--primary))] hover:bg-[hsl(var(--secondary))]' : 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))] shadow-[0_8px_18px_hsl(var(--primary)/.14)]'}`} data-testid={testId}>{children}</button>;
}
export function Metric({ label, value, tone = 'plain' }: { label: string; value: string; tone?: 'plain' | 'accent' | 'green' }) {
  return <div className={`rounded-2xl border border-[hsl(var(--border))] p-5 ${tone === 'accent' ? 'bg-[hsl(var(--accent)/.12)]' : tone === 'green' ? 'bg-[hsl(155_38%_91%)]' : 'bg-[hsl(var(--card))]'}`}><p className="font-mono-app text-[10px] uppercase tracking-[.13em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-3 font-display text-3xl tracking-[-.04em] text-[hsl(var(--primary))]" data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}>{value}</p></div>;
}
export function ThresholdRow({ label, threshold, value, applicable }: { label: string; threshold: number; value: number; applicable: boolean }) {
  const pct = Math.min(100, Math.round((value / threshold) * 100));
  return <div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Threshold ₹{threshold.toLocaleString('en-IN')} crore</p></div><span className={`grid size-8 place-items-center rounded-full ${applicable ? 'bg-[hsl(155_38%_88%)] text-[hsl(155_40%_29%)]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]'}`}>{applicable ? <Check className="size-4" /> : <span className="text-xs">—</span>}</span></div><div className="mt-4 h-2 rounded-full bg-[hsl(var(--muted))]"><div className={`h-2 rounded-full ${applicable ? 'bg-[hsl(155_42%_43%)]' : 'bg-[hsl(var(--primary)/.35)]'}`} style={{ width: `${pct}%` }} /></div><p className="mt-2 text-right font-mono-app text-[10px] text-[hsl(var(--muted-foreground))]">₹{value.toLocaleString('en-IN')} crore</p></div>;
}
export function InfoBox({ children }: { children: ReactNode }) { return <div className="flex items-start gap-3 rounded-2xl border border-[hsl(var(--accent)/.3)] bg-[hsl(var(--accent)/.08)] p-4 text-xs leading-6 text-[hsl(var(--foreground))]"><Info className="mt-1 size-4 shrink-0 text-[hsl(var(--accent-foreground))]" />{children}</div>; }
export function ReviewStatus({ status, note }: { status: string; note?: string | null }) { return <div className="rounded-2xl bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))]"><p className="font-mono-app text-[10px] uppercase tracking-[.15em] text-[hsl(var(--primary-foreground)/.55)]">Independent review</p><div className="mt-4 flex items-center justify-between gap-4"><p className="font-display text-3xl capitalize">{status.replace('_', ' ')}</p><StatusPill status={status} /></div>{note && <p className="mt-4 border-t border-[hsl(var(--primary-foreground)/.15)] pt-4 text-sm leading-6 text-[hsl(var(--primary-foreground)/.7)]">{note}</p>}</div>; }
export function NextLink({ href, children, testId }: { href: string; children: ReactNode; testId: string }) { return <Link href={href} className="group inline-flex items-center gap-2 text-sm font-semibold text-[hsl(var(--primary))]" data-testid={testId}>{children}<ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link>; }